import type { Metadata } from "next";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { archivoBlack, sora } from "@/fonts";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import AuthProvider from "@/context/AuthProvider";
import { createClient } from "@/lib/supabase/server";

config.autoAddCss = false;

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const profile = user
    ? (
        await supabase.from("profiles").select("*").eq("id", user.id).single()
      ).data
    : null;

  return (
    <html
      lang="en"
      className={`${archivoBlack.variable} ${sora.variable} h-full antialiased`}
    >
      <AuthProvider initialUser={user} initialProfile={profile}>
        <body className="selection:bg-primary">
          <div className="flex min-h-dvh flex-col">
            <Header />
            <main className="flex flex-1 flex-col justify-center">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}

export { metadata };
export default RootLayout;
