import type { Metadata } from 'next';
import { anton, archivoBlack, epilogue, sora } from '@/fonts';
import '@/styles/globals.css';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${anton.variable} ${archivoBlack.variable} ${epilogue.variable} ${sora.variable} h-full antialiased`}>
      <body>{children}</body>
    </html>
  );
}

export { metadata };
export default RootLayout;
